[package]
name = "physicsjank"
version = "0.1.0"
edition = "2021"

[dependencies]
catppuccin = "2.5.1"
nalgebra-glm = { version = "0.19.0", features = ["serde-serialize"] }
raylib = { version = "5.0.2", features = ["with_serde"] }
serde = "1.0.215"
serde_json = "1.0.133"
